In [11]:
import random
import time
import numpy as np

start_time = time.time()
a = []
b = []
for i in range(0,3):
    a.append([])
    b.append([])
    for j in range(0,3):
        val = random.randint(0,100)
        val1 = random.randint(0,100)
        a[i].append(val)
        b[i].append(val1)
end_time = time.time()
print("Mang a duoc tao bang cach thu  cong la: " , a)
print("Mang b duoc tao bang cach thu cong la: " , b)
print('Tong thoi gian tao mang 2D bang cach thu cong la: %fs' % (end_time - start_time))

start_time1 = time.time()
c = np.random.randint(100,size=(3,3))
d = np.random.randint(100,size=(3,3))
end_time1 = time.time()
print("Mang c duoc tao bang thu vien numpy la: " , c)
print("Mang d duoc tao bang thu vien numpy la: " , d)
print('Tong thoi gian tao mang 2D bang thu vien numpy la: %fs' % (end_time1 - start_time1))

Mang a duoc tao bang cach thu  cong la:  [[43, 96, 15], [32, 83, 11], [42, 87, 73]]
Mang b duoc tao bang cach thu cong la:  [[64, 45, 19], [73, 17, 71], [60, 49, 15]]
Tong thoi gian tao mang 2D bang cach thu cong la: 0.000000s
Mang c duoc tao bang thu vien numpy la:  [[28 59 25]
 [72 14 52]
 [39 18 86]]
Mang d duoc tao bang thu vien numpy la:  [[22 82 21]
 [73  8 73]
 [96 77 57]]
Tong thoi gian tao mang 2D bang thu vien numpy la: 0.000000s


In [12]:
start_time2 = time.time()
ab = []
for i in range(0,3):
    ab.append([])
    for j in range(0,3):
        num = a[i][j] + b[i][j]
        ab[i].append(num)
end_time2 = time.time()
print("Mang a + b duoc tao bang cach thu cong la: " , ab)
print('Tong thoi gian cong 2 mang bang cach thu cong la: %fs' % (end_time2 - start_time2))

start_time3 = time.time()
cd = c + d
end_time3 = time.time()
print("Mang c + d duoc tao bang thu vien numpy la: ", c + d)
print('Tong thoi gian cong 2 mang bang thu vien numpy la: %fs' % (end_time2 - start_time3))

Mang a + b duoc tao bang cach thu cong la:  [[107, 141, 34], [105, 100, 82], [102, 136, 88]]
Tong thoi gian cong 2 mang bang cach thu cong la: 0.000000s
Mang c + d duoc tao bang thu vien numpy la:  [[ 50 141  46]
 [145  22 125]
 [135  95 143]]
Tong thoi gian cong 2 mang bang thu vien numpy la: -0.000997s


In [13]:
start_time4= time.time()
resultA = 0
resultB = 0
lengA = 0
lengB = 0
for i in range(0,3):
    for j in range(0,3):
        resultA += a[i][j]
        resultB += b[i][j]
        lengA += 1
        lengB += 1
resultA /= lengA
resultB /= lengB
end_time4 = time.time()
print('Trung binh cac phan tu trong mang a la: ' , resultA)
print('Trung binh cac phan tu trong mang a la: ' , resultB)
print('Tong thoi gian tinh trung binh bang cach thu cong la: %fs' % (end_time4 - start_time4))

start_time5 = time.time()
resultC = np.mean(c)
resultD = np.mean(d)
end_time5 = time.time()
print('Trung binh cac phan tu trong mang c la: ' , resultC)
print('Trung binh cac phan tu trong mang d la: ' , resultD)
print('Tong thoi gian tinh trung binh bang thu vien numpy la: %fs' % (end_time5 - start_time5))

Trung binh cac phan tu trong mang a la:  53.55555555555556
Trung binh cac phan tu trong mang a la:  45.888888888888886
Tong thoi gian tinh trung binh bang cach thu cong la: 0.000997s
Trung binh cac phan tu trong mang c la:  43.666666666666664
Trung binh cac phan tu trong mang d la:  56.55555555555556
Tong thoi gian tinh trung binh bang thu vien numpy la: 0.000000s


In [3]:
# cách thường dùng
sum = 0
for i in range(len(a)):
    for j in range(len(a)):
        sum += a[i][j]
print("Tong cua mang la: ", sum)

NameError: name 'a' is not defined

In [4]:
import numpy as np
print("Tong cua mang khi dung numpy: ", np.sum(a))

NameError: name 'a' is not defined

In [5]:
import numpy as np
import time

start_time = time.time()
print("MAX = ",np.max(a))
print("MiN = ", np.min(a))
end_time = time.time()
print('Tong thoi gian thuc hien: %fs' % (end_time - start_time))

NameError: name 'a' is not defined

In [6]:
import time

start_time = time.time()
max= -10**9
min = 10**9
for i in range(len(a)):
    for j in range(len(a)):
        if max<a[i][j]:
            max = a[i][j]
        if min>a[i][j]:
            min = a[i][j]
end_time = time.time()
print("MAX = ",max)
print("MIN = ",min)
print('Tong thoi gian thuc hien: %fs' % (end_time - start_time))

NameError: name 'a' is not defined